In [146]:
import requests
import json

# Example: Get All Cards data
url = "https://mtgjson.com/api/v5/AllPrintings.json"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()["data"]

    cards_collected = []
    for set_code, set_info in data.items():
        for card in set_info.get("cards", []):
            cards_collected.append(card)
            if len(cards_collected) == 100:
                    break
    print(cards_collected[0:5])
else:
    print(f"Failed to fetch data: {response.status_code}")

[{'artist': 'Pete Venters', 'artistIds': ['d54c4a1a-c0c5-4834-84db-125d341f3ad8'], 'availability': ['mtgo', 'paper'], 'boosterTypes': ['default'], 'borderColor': 'black', 'colorIdentity': ['W'], 'colors': ['W'], 'convertedManaCost': 7.0, 'edhrecRank': 23082, 'finishes': ['nonfoil'], 'foreignData': [{'flavorText': '„Es ist der Wille aller, und meine Hand, die ihn ausführt."', 'identifiers': {'multiverseId': '148411', 'scryfallId': 'c8d214a2-6bce-4a31-a346-7d9831ff068c'}, 'language': 'German', 'multiverseId': 148411, 'name': 'Ausgewählter der Ahnfrau', 'text': 'Erstschlag (Diese Kreatur fügt Kampfschaden vor Kreaturen ohne Erstschlag zu.)\nWenn der Ausgewählte der Ahnfrau ins Spiel kommt, erhältst du 1 Lebenspunkt für jede Karte in deinem Friedhof dazu.', 'type': 'Kreatur — Mensch, Kleriker'}, {'flavorText': '"La voluntad de todos, realizada por mi mano."', 'identifiers': {'multiverseId': '150317', 'scryfallId': '3f227aa5-cacf-47d0-917a-c6de07ec4fb3'}, 'language': 'Spanish', 'multiverseId': 150317, 'name': 'Elegido de la Antepasada', 'text': 'Daña primero. (Esta criatura hace daño de combate antes que las criaturas sin la habilidad de dañar primero.)\nCuando el Elegido de la Antepasada entre en juego, ganas 1 vida por cada carta en tu cementerio.', 'type': 'Criatura — Clérigo humano'}, {'flavorText': '« La volonté de tous passe par ma main. »', 'identifiers': {'multiverseId': '149934', 'scryfallId': '03da122a-4487-4dcb-94e1-7029206d583c'}, 'language': 'French', 'multiverseId': 149934, 'name': "Élu de l'Ancêtre", 'text': "Initiative (Cette créature inflige des blessures de combat avant les créatures sans l'initiative.)\nQuand l'Élu de l'Ancêtre arrive en jeu, vous gagnez 1 point de vie pour chaque carte dans votre cimetière.", 'type': 'Créature : humain et clerc'}, {'flavorText': '"La volontà di tutti, eseguita per mano mia."', 'identifiers': {'multiverseId': '148794', 'scryfallId': '3d078ccc-7d64-42ab-9631-f3270ec1bec1'}, 'language': 'Italian', 'multiverseId': 148794, 'name': "Prescelto dell'Antenata", 'text': "Attacco improvviso (Questa creatura infligge danno da combattimento prima delle creature senza attacco improvviso.)\nQuando il Prescelto dell'Antenata entra in gioco, guadagni 1 punto vita per ogni carta nel tuo cimitero.", 'type': 'Creatura — Chierico Umano'}, {'flavorText': 'すべての意思を、この手で成そう。', 'identifiers': {'multiverseId': '148028', 'scryfallId': '6eac08c0-9201-4931-9b41-f3814c8449d6'}, 'language': 'Japanese', 'multiverseId': 148028, 'name': '祖神に選ばれし者', 'text': '先制攻撃 （このクリーチャーは先制攻撃を持たないクリーチャーよりも先に戦闘ダメージを与える。）\n祖神に選ばれし者が場に出たとき、あなたはあなたの墓地にあるカード１枚につき１点のライフを得る。', 'type': 'クリーチャー — 人間・クレリック'}, {'flavorText': '"A vontade de todos pelas minhas mãos realizada."', 'identifiers': {'multiverseId': '149551', 'scryfallId': 'fd447049-4cd9-4850-a7c0-6051f9672710'}, 'language': 'Portuguese (Brazil)', 'multiverseId': 149551, 'name': 'Eleito da Ancestral', 'text': 'Iniciativa (Esta criatura causa dano de combate antes de criaturas sem a habilidade de iniciativa.)\nQuando Eleito da Ancestral entra em jogo, você ganha 1 ponto de vida para cada card em seu cemitério.', 'type': 'Criatura — Humano Clérigo'}, {'flavorText': '"Общая воля моей рукой вершится".', 'identifiers': {'multiverseId': '149168', 'scryfallId': 'a6b3f7cd-5a8a-441c-a84a-3a5d7ad860f9'}, 'language': 'Russian', 'multiverseId': 149168, 'name': 'Избранник Прародителя', 'text': 'Первый удар (Это существо наносит боевые повреждения раньше существ без Первого удара.)\nКогда Избранник Прародителя входит в игру, вы получаете 1 жизнь за каждую карту на вашем кладбище.', 'type': 'Существо — Человек Священник'}, {'flavorText': '「众生所愿，吾手所圆。」', 'identifiers': {'multiverseId': '147645', 'scryfallId': '1e59f85a-ca42-46a1-a6aa-01bc9afd6f6c'}, 'language': 'Chinese Simplified', 'multiverseId': 147645, 'name': '祖灵的爱民', 'text': '先攻（此生物会比不具先攻异能的生物提前造成战斗伤害。）\n当祖灵的爱民进场时，你坟墓场中每有一张牌，你便获得1点生命。', 'type': '生物～人类／僧侣'}], 'frameVersion': '2003', 'hasFoil': False, 'hasNonFoil': True, 'identifiers': {'cardKingdomId': '122719', 'cardsphereId': '20', 'deckboxId': '2676', 'mcmId': '16165', 'mcmMetaId': '156', 'mtgjsonFoilVersionId': 'b7c19924-b4bf-56fc-aa73-f586e940bd42', 'mtgjsonV4Id': 'ad41be73-582f-58ed-abd4-a88c1f616ac3', 'mtgoFoilId': '27501', 'mtgoId': '27500', 'multiverseId': '130550', 'scryfallCardBackId': '0aeebaf5-8c7d-4636-9e82-8c27447861f7', 'scryfallId': '7a5cd03c-4227-4551-aa4b-7d119f0468b5', 'scryfallIllustrationId': 'be2f7173-c8b7-4172-a388-9b2c6b3c16e5', 'scryfallOracleId': 'fc2ccab7-cab1-4463-b73d-898070136d74', 'tcgplayerProductId': '15032'}, 'isReprint': True, 'keywords': ['First strike'], 'language': 'English', 'layout': 'normal', 'legalities': {'commander': 'Legal', 'duel': 'Legal', 'legacy': 'Legal', 'modern': 'Legal', 'oathbreaker': 'Legal', 'predh': 'Legal', 'premodern': 'Legal', 'vintage': 'Legal'}, 'manaCost': '{5}{W}{W}', 'manaValue': 7.0, 'name': "Ancestor's Chosen", 'number': '1', 'originalText': "First strike\nWhen Ancestor's Chosen comes into play, you gain 1 life for each card in your graveyard.", 'originalType': 'Creature - Human Cleric', 'power': '4', 'printings': ['10E', 'JUD', 'UMA'], 'purchaseUrls': {'cardKingdom': 'https://mtgjson.com/links/9fb51af0ad6f0736', 'cardmarket': 'https://mtgjson.com/links/ace8861194ee0b6a', 'tcgplayer': 'https://mtgjson.com/links/4843cea124a0d515'}, 'rarity': 'uncommon', 'setCode': '10E', 'sourceProducts': {'nonfoil': ['3a10f018-17fe-56a7-91ba-b4bd98678c8d', '4831adbb-c0af-5d27-b407-19f2f7805949', 'c690e178-661d-5e17-9b29-a5bf6319a844']}, 'subtypes': ['Human', 'Cleric'], 'supertypes': [], 'text': 'First strike (This creature deals combat damage before creatures without first strike.)\nWhen this creature enters, you gain 1 life for each card in your graveyard.', 'toughness': '4', 'type': 'Creature — Human Cleric', 'types': ['Creature'], 'uuid': '5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c', 'variations': ['b7c19924-b4bf-56fc-aa73-f586e940bd42']}, {'artist': 'Pete Venters', 'artistIds': ['d54c4a1a-c0c5-4834-84db-125d341f3ad8'], 'availability': ['mtgo', 'paper'], 'boosterTypes': ['default'], 'borderColor': 'black', 'colorIdentity': ['W'], 'colors': ['W'], 'convertedManaCost': 7.0, 'edhrecRank': 23082, 'finishes': ['foil'], 'flavorText': '"The will of all, by my hand done."', 'foreignData': [], 'frameVersion': '2003', 'hasFoil': True, 'hasNonFoil': False, 'identifiers': {'cardKingdomFoilId': '123087', 'cardsphereFoilId': '19', 'deckboxId': '2676', 'mcmId': '16165', 'mcmMetaId': '156', 'mtgjsonNonFoilVersionId': '5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c', 'mtgjsonV4Id': 'fcd5d3ab-d58e-5cea-861a-cb377f37bf83', 'scryfallCardBackId': '0aeebaf5-8c7d-4636-9e82-8c27447861f7', 'scryfallId': '82072a1d-c1ab-4b4f-875f-d0591447e0a4', 'scryfallIllustrationId': 'be2f7173-c8b7-4172-a388-9b2c6b3c16e5', 'scryfallOracleId': 'fc2ccab7-cab1-4463-b73d-898070136d74', 'tcgplayerProductId': '15032'}, 'isReprint': True, 'keywords': ['First strike'], 'language': 'English', 'layout': 'normal', 'legalities': {'commander': 'Legal', 'duel': 'Legal', 'legacy': 'Legal', 'modern': 'Legal', 'oathbreaker': 'Legal', 'predh': 'Legal', 'premodern': 'Legal', 'vintage': 'Legal'}, 'manaCost': '{5}{W}{W}', 'manaValue': 7.0, 'name': "Ancestor's Chosen", 'number': '1★', 'power': '4', 'printings': ['10E', 'JUD', 'UMA'], 'purchaseUrls': {'cardKingdomFoil': 'https://mtgjson.com/links/4e3f626b14b25f54', 'cardmarket': 'https://mtgjson.com/links/756ef2c8826847f5', 'tcgplayer': 'https://mtgjson.com/links/74fc1dd3bbb80489'}, 'rarity': 'uncommon', 'setCode': '10E', 'sourceProducts': {'foil': ['c5cd29de-5ec9-5e13-b8eb-40e3a9f79f9a', 'c690e178-661d-5e17-9b29-a5bf6319a844']}, 'subtypes': ['Human', 'Cleric'], 'supertypes': [], 'text': 'First strike (This creature deals combat damage before creatures without first strike.)\nWhen this creature enters, you gain 1 life for each card in your graveyard.', 'toughness': '4', 'type': 'Creature — Human Cleric', 'types': ['Creature'], 'uuid': 'b7c19924-b4bf-56fc-aa73-f586e940bd42', 'variations': ['5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c']}, {'artist': 'Volkan Baǵa', 'artistIds': ['93bec3c0-0260-4d31-8064-5d01efb4153f'], 'availability': ['mtgo', 'paper'], 'boosterTypes': ['default'], 'borderColor': 'black', 'colorIdentity': ['W'], 'colors': ['W'], 'convertedManaCost': 5.0, 'edhrecRank': 18098, 'edhrecSaltiness': 0.12, 'finishes': ['nonfoil'], 'flavorText': 'Every tear shed is a drop of immortality.', 'foreignData': [{'flavorText': 'Jede ihrer Tränen ist ein Tropfen Unsterblichkeit.', 'identifiers': {'multiverseId': '148412', 'scryfallId': '528ac57a-a8e9-448a-8cfd-65de45b46942'}, 'language': 'German', 'multiverseId': 148412, 'name': 'Engel der Gnade', 'text': 'Fliegend (Diese Kreatur kann außer von fliegenden Kreaturen und Kreaturen mit Reichweite nicht geblockt werden.)\nWenn der Engel der Gnade ins Spiel kommt, erhältst du 3 Lebenspunkte dazu.', 'type': 'Kreatur — Engel'}, {'flavorText': 'Cada lágrima derramada es una gota de inmortalidad.', 'identifiers': {'multiverseId': '150318', 'scryfallId': '912bbca9-d3ef-40e7-8228-1191c6f3228f'}, 'language': 'Spanish', 'multiverseId': 150318, 'name': 'Ángel de piedad', 'text': 'Vuela. (Esta criatura no puede ser bloqueada excepto por criaturas que tengan la habilidad de volar o alcance.)\nCuando el Ángel de piedad entre en juego, gana 3 vidas.', 'type': 'Criatura — Ángel'}, {'flavorText': "Chaque larme versée est une goutte d'immortalité.", 'identifiers': {'multiverseId': '149935', 'scryfallId': '64835af8-f6f3-4a7c-a944-74b4252b20c6'}, 'language': 'French', 'multiverseId': 149935, 'name': 'Ange de miséricorde', 'text': "Vol (Cette créature ne peut être bloquée que par des créatures avec le vol ou la portée.)\nQuand l'Ange de miséricorde arrive en jeu, vous gagnez 3 points de vie.", 'type': 'Créature : ange'}, {'flavorText': "Ogni lacrima versata è una goccia d'immortalità.", 'identifiers': {'multiverseId': '148795', 'scryfallId': '12fefa2c-88e9-4261-8924-a64156780ea6'}, 'language': 'Italian', 'multiverseId': 148795, 'name': 'Angelo della Misericordia', 'text': "Volare (Questa creatura non può essere bloccata tranne che da creature con volare o raggiungere.)\nQuando l'Angelo della Misericordia entra in gioco, guadagni 3 punti vita.", 'type': 'Creatura — Angelo'}, {'flavorText': '流す涙は不死の滴。', 'identifiers': {'multiverseId': '148029', 'scryfallId': '80d6d63b-58be-49e5-8aba-7ec6b4bd5722'}, 'language': 'Japanese', 'multiverseId': 148029, 'name': '慈悲の天使', 'text': '飛行 （このクリーチャーは飛行や到達を持たないクリーチャーによってブロックされない。）\n慈悲の天使が場に出たとき、あなたは３点のライフを得る。', 'type': 'クリーチャー — 天使'}, {'flavorText': 'Cada lágrima derramada é uma gota de imortalidade.', 'identifiers': {'multiverseId': '149552', 'scryfallId': '4536c1c2-00f0-46fb-9898-d1237a9c7a2f'}, 'language': 'Portuguese (Brazil)', 'multiverseId': 149552, 'name': 'Anjo de Misericórdia', 'text': 'Voar (Esta criatura só pode ser bloqueada por criaturas com a habilidade de voar ou alcance.)\nQuando Anjo de Misericórdia entra em jogo, você ganha 3 pontos de vida.', 'type': 'Criatura — Anjo'}, {'flavorText': 'Каждая пролитая слеза это капля бессмертия.', 'identifiers': {'multiverseId': '149169', 'scryfallId': '58429920-9b38-454d-9cb2-912a509d7795'}, 'language': 'Russian', 'multiverseId': 149169, 'name': 'Ангел Милосердия', 'text': 'Полет (Это существо может быть заблокировано только существом с Полетом или Захватом.)\nКогда Ангел Милосердия входит в игру, вы получаете 3 жизни.', 'type': 'Существо — Ангел'}, {'flavorText': '每颗泪珠都是一滴不朽。', 'identifiers': {'multiverseId': '147646', 'scryfallId': '18bd3568-e398-44d7-9ae2-002acfb17324'}, 'language': 'Chinese Simplified', 'multiverseId': 147646, 'name': '慈悲天使', 'text': '飞行（只有具飞行或延势异能的生物才能阻挡它。）\n当慈悲天使进场时，你获得3点生命。', 'type': '生物～天使'}], 'frameVersion': '2003', 'hasFoil': False, 'hasNonFoil': True, 'identifiers': {'cardKingdomId': '122720', 'cardsphereId': '22', 'deckboxId': '7129', 'mcmId': '16166', 'mcmMetaId': '176', 'mtgjsonFoilVersionId': '8fd4e2eb-3eb4-50ea-856b-ef638fa47f8a', 'mtgjsonV4Id': '9eb2e54c-a12b-5e88-a9c0-d8c84c52d59c', 'mtgoFoilId': '26993', 'mtgoId': '26992', 'multiverseId': '129465', 'scryfallCardBackId': '0aeebaf5-8c7d-4636-9e82-8c27447861f7', 'scryfallId': '8f7980d4-da43-4d6d-ad16-14b8a34ae91d', 'scryfallIllustrationId': 'e4d6c53f-e936-4be8-8b70-47c2be863b20', 'scryfallOracleId': 'a2daaf32-dbfe-4618-892e-0da24f63a44a', 'tcgplayerProductId': '15033'}, 'isReprint': True, 'keywords': ['Flying'], 'language': 'English', 'layout': 'normal', 'legalities': {'brawl': 'Legal', 'commander': 'Legal', 'duel': 'Legal', 'gladiator': 'Legal', 'historic': 'Legal', 'legacy': 'Legal', 'modern': 'Legal', 'oathbreaker': 'Legal', 'pauper': 'Legal', 'paupercommander': 'Legal', 'penny': 'Legal', 'predh': 'Legal', 'premodern': 'Legal', 'timeless': 'Legal', 'vintage': 'Legal'}, 'manaCost': '{4}{W}', 'manaValue': 5.0, 'name': 'Angel of Mercy', 'number': '2', 'originalText': 'Flying\nWhen Angel of Mercy comes into play, you gain 3 life.', 'originalType': 'Creature - Angel', 'power': '3', 'printings': ['10E', '8ED', '9ED', 'DDC', 'DVD', 'IMA', 'INV', 'J25', 'JMP', 'P02', 'PLST', 'PS11', 'PSAL', 'S99'], 'purchaseUrls': {'cardKingdom': 'https://mtgjson.com/links/027095d094e58f5b', 'cardmarket': 'https://mtgjson.com/links/f6fb5098e1cd1b1e', 'tcgplayer': 'https://mtgjson.com/links/56c4b57293f350ef'}, 'rarity': 'uncommon', 'setCode': '10E', 'sourceProducts': {'nonfoil': ['3210bf43-80f4-5ae4-be77-f65848791205', '3a10f018-17fe-56a7-91ba-b4bd98678c8d', '4831adbb-c0af-5d27-b407-19f2f7805949', 'c690e178-661d-5e17-9b29-a5bf6319a844']}, 'subtypes': ['Angel'], 'supertypes': [], 'text': 'Flying\nWhen this creature enters, you gain 3 life.', 'toughness': '3', 'type': 'Creature — Angel', 'types': ['Creature'], 'uuid': '57aaebc1-850c-503d-9f6e-bb8d00d8bf7c', 'variations': ['8fd4e2eb-3eb4-50ea-856b-ef638fa47f8a']}, {'artist': 'Volkan Baǵa', 'artistIds': ['93bec3c0-0260-4d31-8064-5d01efb4153f'], 'availability': ['mtgo', 'paper'], 'boosterTypes': ['default'], 'borderColor': 'black', 'colorIdentity': ['W'], 'colors': ['W'], 'convertedManaCost': 5.0, 'edhrecRank': 18098, 'edhrecSaltiness': 0.12, 'finishes': ['foil'], 'flavorText': 'Every tear shed is a drop of immortality.', 'foreignData': [], 'frameVersion': '2003', 'hasFoil': True, 'hasNonFoil': False, 'identifiers': {'cardKingdomFoilId': '123088', 'cardsphereFoilId': '21', 'deckboxId': '7129', 'mcmId': '16166', 'mcmMetaId': '176', 'mtgjsonNonFoilVersionId': '57aaebc1-850c-503d-9f6e-bb8d00d8bf7c', 'mtgjsonV4Id': 'e2be2630-ada5-57c7-8612-0356dfa75ce5', 'scryfallCardBackId': '0aeebaf5-8c7d-4636-9e82-8c27447861f7', 'scryfallId': 'b0157252-6949-4f03-a15c-c168512123a8', 'scryfallIllustrationId': 'e4d6c53f-e936-4be8-8b70-47c2be863b20', 'scryfallOracleId': 'a2daaf32-dbfe-4618-892e-0da24f63a44a', 'tcgplayerProductId': '15033'}, 'isReprint': True, 'keywords': ['Flying'], 'language': 'English', 'layout': 'normal', 'legalities': {'brawl': 'Legal', 'commander': 'Legal', 'duel': 'Legal', 'gladiator': 'Legal', 'historic': 'Legal', 'legacy': 'Legal', 'modern': 'Legal', 'oathbreaker': 'Legal', 'pauper': 'Legal', 'paupercommander': 'Legal', 'penny': 'Legal', 'predh': 'Legal', 'premodern': 'Legal', 'timeless': 'Legal', 'vintage': 'Legal'}, 'manaCost': '{4}{W}', 'manaValue': 5.0, 'name': 'Angel of Mercy', 'number': '2★', 'power': '3', 'printings': ['10E', '8ED', '9ED', 'DDC', 'DVD', 'IMA', 'INV', 'J25', 'JMP', 'P02', 'PLST', 'PS11', 'PSAL', 'S99'], 'purchaseUrls': {'cardKingdomFoil': 'https://mtgjson.com/links/24872a315d0f0570', 'cardmarket': 'https://mtgjson.com/links/a3b3231bd55530aa', 'tcgplayer': 'https://mtgjson.com/links/0f9617baa94a51b9'}, 'rarity': 'uncommon', 'setCode': '10E', 'sourceProducts': {'foil': ['c5cd29de-5ec9-5e13-b8eb-40e3a9f79f9a', 'c690e178-661d-5e17-9b29-a5bf6319a844']}, 'subtypes': ['Angel'], 'supertypes': [], 'text': 'Flying\nWhen this creature enters, you gain 3 life.', 'toughness': '3', 'type': 'Creature — Angel', 'types': ['Creature'], 'uuid': '8fd4e2eb-3eb4-50ea-856b-ef638fa47f8a', 'variations': ['57aaebc1-850c-503d-9f6e-bb8d00d8bf7c']}, {'artist': 'Mark Zug', 'artistIds': ['48e2b98c-5467-4671-bd42-4c3746115117'], 'availability': ['mtgo', 'paper'], 'boosterTypes': ['default'], 'borderColor': 'black', 'colorIdentity': ['W'], 'colors': ['W'], 'convertedManaCost': 3.0, 'edhrecRank': 24561, 'edhrecSaltiness': 0.12, 'finishes': ['nonfoil'], 'flavorText': 'Only the warrior who can admit mortal weakness will be bolstered by immortal strength.', 'foreignData': [{'flavorText': 'Nur demjenigen Krieger, der sterbliche Schwäche zugeben kann, wird unsterbliche Stärke gewährt.', 'identifiers': {'multiverseId': '148414', 'scryfallId': '9e19c048-f825-48ba-9957-dbf5e133e280'}, 'language': 'German', 'multiverseId': 148414, 'name': 'Himmlischer Segen', 'text': 'Eine Kreatur deiner Wahl erhält +3/+3 und Flugfähigkeit bis zum Ende des Zuges. (Sie kann außer von fliegenden Kreaturen und Kreaturen mit Reichweite nicht geblockt werden.)', 'type': 'Hexerei'}, {'flavorText': 'Sólo el guerrero que pueda admitir debilidad mortal será auxiliado con fuerza inmortal.', 'identifiers': {'multiverseId': '150319', 'scryfallId': '5f4da2bd-db8d-4eb6-9ff6-8cbcd49a9463'}, 'language': 'Spanish', 'multiverseId': 150319, 'name': 'Bendición angélica', 'text': 'La criatura objetivo obtiene +3/+3 y gana la habilidad de volar hasta el final del turno. (No puede ser bloqueada excepto por criaturas que tengan la habilidad de volar o alcance.)', 'type': 'Conjuro'}, {'flavorText': 'Seul le guerrier qui admet une faiblesse mortelle peut recevoir la force immortelle.', 'identifiers': {'multiverseId': '149936', 'scryfallId': '42cdc454-8326-4386-9e79-381e6ed6136c'}, 'language': 'French', 'multiverseId': 149936, 'name': 'Bénédiction angélique', 'text': "La créature ciblée gagne +3/+3 et acquiert le vol jusqu'à la fin du tour. (Elle ne peut être bloquée que par des créatures avec le vol ou la portée.)", 'type': 'Rituel'}, {'flavorText': 'Solo il guerriero capace di ammettere la propria fragilità mortale sarà sostenuto dalla forza immortale.', 'identifiers': {'multiverseId': '148797', 'scryfallId': '03ca8824-158c-4fee-89c8-e0dd427f2c9d'}, 'language': 'Italian', 'multiverseId': 148797, 'name': 'Benedizione Angelica', 'text': 'Una creatura bersaglio prende +3/+3 e ha volare fino alla fine del turno. (Non può essere bloccata tranne che da creature con volare o raggiungere.)', 'type': 'Stregoneria'}, {'flavorText': '必滅の身であることを知っている戦士だけが、不滅の力に支えられる。', 'identifiers': {'multiverseId': '148031', 'scryfallId': 'cc76004c-89b4-485d-9f53-c68e1818f67e'}, 'language': 'Japanese', 'multiverseId': 148031, 'name': '天使の祝福', 'text': 'クリーチャー１体を対象とする。それはターン終了時まで＋３/＋３の修整を受けるとともに飛行を得る。 （それは飛行や到達を持たないクリーチャーによってブロックされない。）', 'type': 'ソーサリー'}, {'flavorText': 'Somente o guerreiro que for capaz de admitir sua própria fragilidade mortal será favorecido com força imortal.', 'identifiers': {'multiverseId': '149553', 'scryfallId': '93e90c33-4634-4742-9741-9832d620c3ee'}, 'language': 'Portuguese (Brazil)', 'multiverseId': 149553, 'name': 'Bênção Angelical', 'text': 'A criatura alvo recebe +3/+3 e ganha a habilidade de voar até o final do turno. (Ela só pode ser bloqueada por criaturas com a habilidade de voar ou alcance.)', 'type': 'Feitiço'}, {'flavorText': 'Только тот воин, что признает в себе слабости смертных, будет наделен силой бессмертных.', 'identifiers': {'multiverseId': '149170', 'scryfallId': '401bb417-858e-4ad4-b14b-4b96119d1c59'}, 'language': 'Russian', 'multiverseId': 149170, 'name': 'Благословение Ангела', 'text': 'Целевое существо получает +3/+3 и Полет до конца хода. (Оно может быть заблокировано только существом с Полетом или Захватом.)', 'type': 'Волшебство'}, {'flavorText': '只有勇于正视自身致命弱点的战士，才能受到超凡力量的庇护。', 'identifiers': {'multiverseId': '147648', 'scryfallId': '0aea70ec-2317-4856-858b-62f44b29c30f'}, 'language': 'Chinese Simplified', 'multiverseId': 147648, 'name': '天使的祝福', 'text': '目标生物得+3/+3并获得飞行异能直到回合结束。 （只有具飞行或延势异能的生物才能阻挡它。）', 'type': '法术'}], 'frameVersion': '2003', 'hasFoil': False, 'hasNonFoil': True, 

In [147]:
cards_collected[0]

{'artist': 'Pete Venters',
 'artistIds': ['d54c4a1a-c0c5-4834-84db-125d341f3ad8'],
 'availability': ['mtgo', 'paper'],
 'boosterTypes': ['default'],
 'borderColor': 'black',
 'colorIdentity': ['W'],
 'colors': ['W'],
 'convertedManaCost': 7.0,
 'edhrecRank': 23082,
 'finishes': ['nonfoil'],
 'foreignData': [{'flavorText': '„Es ist der Wille aller, und meine Hand, die ihn ausführt."',
   'identifiers': {'multiverseId': '148411',
    'scryfallId': 'c8d214a2-6bce-4a31-a346-7d9831ff068c'},
   'language': 'German',
   'multiverseId': 148411,
   'name': 'Ausgewählter der Ahnfrau',
   'text': 'Erstschlag (Diese Kreatur fügt Kampfschaden vor Kreaturen ohne Erstschlag zu.)\nWenn der Ausgewählte der Ahnfrau ins Spiel kommt, erhältst du 1 Lebenspunkt für jede Karte in deinem Friedhof dazu.',
   'type': 'Kreatur — Mensch, Kleriker'},
  {'flavorText': '"La voluntad de todos, realizada por mi mano."',
   'identifiers': {'multiverseId': '150317',
    'scryfallId': '3f227aa5-cacf-47d0-917a-c6de07ec4fb3'},
   'language': 'Spanish',
   'multiverseId': 150317,
   'name': 'Elegido de la Antepasada',
   'text': 'Daña primero. (Esta criatura hace daño de combate antes que las criaturas sin la habilidad de dañar primero.)\nCuando el Elegido de la Antepasada entre en juego, ganas 1 vida por cada carta en tu cementerio.',
   'type': 'Criatura — Clérigo humano'},
  {'flavorText': '« La volonté de tous passe par ma main. »',
   'identifiers': {'multiverseId': '149934',
    'scryfallId': '03da122a-4487-4dcb-94e1-7029206d583c'},
   'language': 'French',
   'multiverseId': 149934,
   'name': "Élu de l'Ancêtre",
   'text': "Initiative (Cette créature inflige des blessures de combat avant les créatures sans l'initiative.)\nQuand l'Élu de l'Ancêtre arrive en jeu, vous gagnez 1 point de vie pour chaque carte dans votre cimetière.",
   'type': 'Créature : humain et clerc'},
  {'flavorText': '"La volontà di tutti, eseguita per mano mia."',
   'identifiers': {'multiverseId': '148794',
    'scryfallId': '3d078ccc-7d64-42ab-9631-f3270ec1bec1'},
   'language': 'Italian',
   'multiverseId': 148794,
   'name': "Prescelto dell'Antenata",
   'text': "Attacco improvviso (Questa creatura infligge danno da combattimento prima delle creature senza attacco improvviso.)\nQuando il Prescelto dell'Antenata entra in gioco, guadagni 1 punto vita per ogni carta nel tuo cimitero.",
   'type': 'Creatura — Chierico Umano'},
  {'flavorText': 'すべての意思を、この手で成そう。',
   'identifiers': {'multiverseId': '148028',
    'scryfallId': '6eac08c0-9201-4931-9b41-f3814c8449d6'},
   'language': 'Japanese',
   'multiverseId': 148028,
   'name': '祖神に選ばれし者',
   'text': '先制攻撃 （このクリーチャーは先制攻撃を持たないクリーチャーよりも先に戦闘ダメージを与える。）\n祖神に選ばれし者が場に出たとき、あなたはあなたの墓地にあるカード１枚につき１点のライフを得る。',
   'type': 'クリーチャー — 人間・クレリック'},
  {'flavorText': '"A vontade de todos pelas minhas mãos realizada."',
   'identifiers': {'multiverseId': '149551',
    'scryfallId': 'fd447049-4cd9-4850-a7c0-6051f9672710'},
   'language': 'Portuguese (Brazil)',
   'multiverseId': 149551,
   'name': 'Eleito da Ancestral',
   'text': 'Iniciativa (Esta criatura causa dano de combate antes de criaturas sem a habilidade de iniciativa.)\nQuando Eleito da Ancestral entra em jogo, você ganha 1 ponto de vida para cada card em seu cemitério.',
   'type': 'Criatura — Humano Clérigo'},
  {'flavorText': '"Общая воля моей рукой вершится".',
   'identifiers': {'multiverseId': '149168',
    'scryfallId': 'a6b3f7cd-5a8a-441c-a84a-3a5d7ad860f9'},
   'language': 'Russian',
   'multiverseId': 149168,
   'name': 'Избранник Прародителя',
   'text': 'Первый удар (Это существо наносит боевые повреждения раньше существ без Первого удара.)\nКогда Избранник Прародителя входит в игру, вы получаете 1 жизнь за каждую карту на вашем кладбище.',
   'type': 'Существо — Человек Священник'},
  {'flavorText': '「众生所愿，吾手所圆。」',
   'identifiers': {'multiverseId': '147645',
    'scryfallId': '1e59f85a-ca42-46a1-a6aa-01bc9afd6f6c'},
   'language': 'Chinese Simplified',
   'multiverseId': 147645,
   'name': '祖灵的爱民',
   'text': '先攻（此生物会比不具先攻异能的生物提前造成战斗伤害。）\n当祖灵的爱民进场时，你坟墓场中每有一张牌，你便获得1点生命。',
   'type': '生物～人类／僧侣'}],
 'frameVersion': '2003',
 'hasFoil': False,
 'hasNonFoil': True,
 'identifiers': {'cardKingdomId': '122719',
  'cardsphereId': '20',
  'deckboxId': '2676',
  'mcmId': '16165',
  'mcmMetaId': '156',
  'mtgjsonFoilVersionId': 'b7c19924-b4bf-56fc-aa73-f586e940bd42',
  'mtgjsonV4Id': 'ad41be73-582f-58ed-abd4-a88c1f616ac3',
  'mtgoFoilId': '27501',
  'mtgoId': '27500',
  'multiverseId': '130550',
  'scryfallCardBackId': '0aeebaf5-8c7d-4636-9e82-8c27447861f7',
  'scryfallId': '7a5cd03c-4227-4551-aa4b-7d119f0468b5',
  'scryfallIllustrationId': 'be2f7173-c8b7-4172-a388-9b2c6b3c16e5',
  'scryfallOracleId': 'fc2ccab7-cab1-4463-b73d-898070136d74',
  'tcgplayerProductId': '15032'},
 'isReprint': True,
 'keywords': ['First strike'],
 'language': 'English',
 'layout': 'normal',
 'legalities': {'commander': 'Legal',
  'duel': 'Legal',
  'legacy': 'Legal',
  'modern': 'Legal',
  'oathbreaker': 'Legal',
  'predh': 'Legal',
  'premodern': 'Legal',
  'vintage': 'Legal'},
 'manaCost': '{5}{W}{W}',
 'manaValue': 7.0,
 'name': "Ancestor's Chosen",
 'number': '1',
 'originalText': "First strike\nWhen Ancestor's Chosen comes into play, you gain 1 life for each card in your graveyard.",
 'originalType': 'Creature - Human Cleric',
 'power': '4',
 'printings': ['10E', 'JUD', 'UMA'],
 'purchaseUrls': {'cardKingdom': 'https://mtgjson.com/links/9fb51af0ad6f0736',
  'cardmarket': 'https://mtgjson.com/links/ace8861194ee0b6a',
  'tcgplayer': 'https://mtgjson.com/links/4843cea124a0d515'},
 'rarity': 'uncommon',
 'setCode': '10E',
 'sourceProducts': {'nonfoil': ['3a10f018-17fe-56a7-91ba-b4bd98678c8d',
   '4831adbb-c0af-5d27-b407-19f2f7805949',
   'c690e178-661d-5e17-9b29-a5bf6319a844']},
 'subtypes': ['Human', 'Cleric'],
 'supertypes': [],
 'text': 'First strike (This creature deals combat damage before creatures without first strike.)\nWhen this creature enters, you gain 1 life for each card in your graveyard.',
 'toughness': '4',
 'type': 'Creature — Human Cleric',
 'types': ['Creature'],
 'uuid': '5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c',
 'variations': ['b7c19924-b4bf-56fc-aa73-f586e940bd42']}

In [148]:
import os

BATCH_SIZE = 1000
OUTPUT_DIR = "mtgjson_card_batches"

# Create output directory
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Download AllPrintings.json
url = "https://mtgjson.com/api/v5/AllPrintings.json"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()["data"]

    cards_collected = []
    batch_number = 1

    for set_code, set_info in data.items():
        for card in set_info.get("cards", []):
            cards_collected.append(card)
            if len(cards_collected) == BATCH_SIZE:
                # Write this batch to a file
                filename = os.path.join(OUTPUT_DIR, f"cards_batch_{batch_number:03}.json")
                with open(filename, "w") as f:
                    json.dump(cards_collected, f, indent=2)
                print(f"Saved {filename} with {len(cards_collected)} cards")
                cards_collected = []
                batch_number += 1

    # Save remaining cards
    if cards_collected:
        filename = os.path.join(OUTPUT_DIR, f"cards_batch_{batch_number:03}.json")
        with open(filename, "w") as f:
            json.dump(cards_collected, f, indent=2)
        print(f"Saved final {filename} with {len(cards_collected)} cards")

Saved mtgjson_card_batches/cards_batch_001.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_002.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_003.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_004.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_005.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_006.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_007.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_008.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_009.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_010.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_011.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_012.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_013.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_014.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_015.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_016.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_017.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_018.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_019.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_020.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_021.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_022.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_023.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_024.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_025.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_026.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_027.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_028.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_029.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_030.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_031.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_032.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_033.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_034.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_035.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_036.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_037.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_038.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_039.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_040.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_041.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_042.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_043.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_044.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_045.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_046.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_047.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_048.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_049.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_050.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_051.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_052.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_053.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_054.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_055.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_056.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_057.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_058.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_059.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_060.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_061.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_062.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_063.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_064.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_065.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_066.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_067.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_068.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_069.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_070.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_071.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_072.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_073.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_074.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_075.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_076.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_077.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_078.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_079.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_080.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_081.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_082.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_083.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_084.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_085.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_086.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_087.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_088.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_089.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_090.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_091.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_092.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_093.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_094.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_095.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_096.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_097.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_098.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_099.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_100.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_101.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_102.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_103.json with 1000 cards
Saved mtgjson_card_batches/cards_batch_104.json with 1000 cards
Saved final mtgjson_card_batches/cards_batch_105.json with 308 cards

In [149]:
def extract_card_info(card):
    legalities = card.get("legalities", {})
    legal_in = [fmt for fmt, status in legalities.items() if status == "Legal"]

    return {
        "uuid": card.get("uuid"),
        "name": card.get("name"),
        "type": card.get("type"),
        "types": card.get("types", []),
        "subtypes": card.get("subtypes", []),
        "manaCost": card.get("manaCost"),
        "convertedManaCost": card.get("convertedManaCost"),
        "colors": card.get("colors", []),
        "colorIdentity": card.get("colorIdentity", []),
        "text": card.get("text"),
        "power": card.get("power"),
        "toughness": card.get("toughness"),
        "loyalty": card.get("loyalty"),
        "rarity": card.get("rarity"),
        "isLegendary": card.get("isLegendary", False),
        "layout": card.get("layout"),
        "setCode": card.get("setCode"),
        "legalities": legal_in
    }

In [150]:
import polars as pl

def load_all_cards_from_folder(folder_path):
    data = []

    for file_name in os.listdir(folder_path):
        if file_name.endswith(".json"):
            with open(os.path.join(folder_path, file_name), "r", encoding="utf-8") as f:
                try:
                    cards = json.load(f)
                    if isinstance(cards, dict):
                        # Handles a JSON file with one card
                        data.append(extract_card_info(cards))
                    elif isinstance(cards, list):
                        for card in cards:
                            data.append(extract_card_info(card))
                except Exception as e:
                    print(f"Failed to load {file_name}: {e}")

    return pl.DataFrame(data)

In [151]:
cards_df = load_all_cards_from_folder(folder_path="mtgjson_card_batches")
cards_df

shape: (104_308, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬─────────┬───────────┐
│ uuid       ┆ name       ┆ type       ┆ types      ┆ … ┆ isLegenda ┆ layout ┆ setCode ┆ legalitie │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ry        ┆ ---    ┆ ---     ┆ s         │
│ str        ┆ str        ┆ str        ┆ list[str]  ┆   ┆ ---       ┆ str    ┆ str     ┆ ---       │
│            ┆            ┆            ┆            ┆   ┆ bool      ┆        ┆         ┆ list[str] │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═════════╪═══════════╡
│ 721703e7-d ┆ Cloudsteel ┆ Artifact   ┆ ["Artifact ┆ … ┆ false     ┆ normal ┆ PRM     ┆ ["brawl", │
│ 5c7-5965-8 ┆ Kirin      ┆ Creature — ┆ ", "Creatu ┆   ┆           ┆        ┆         ┆ "commande │
│ 9fd-a03279 ┆            ┆ Equipment  ┆ re"]       ┆   ┆           ┆        ┆         ┆ r", …     │
│ …          ┆            ┆ …          ┆            ┆   ┆           ┆        ┆         ┆ "vint…    │
│ 1ec1eae9-7 ┆ Brilliant  ┆ Sorcery    ┆ ["Sorcery" ┆ … ┆ false     ┆ normal ┆ PRM     ┆ ["brawl", │
│ ffe-5548-a ┆ Restoratio ┆            ┆ ]          ┆   ┆           ┆        ┆         ┆ "commande │
│ 1fd-b596dc ┆ n          ┆            ┆            ┆   ┆           ┆        ┆         ┆ r", …     │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vint…    │
│ 1b1893f8-e ┆ Myojin of  ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ PRM     ┆ ["command │
│ f09-5787-b ┆ Blooming   ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ d67-4819cb ┆ Dawn       ┆ Spirit     ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ 200584c2-7 ┆ Farewell   ┆ Sorcery    ┆ ["Sorcery" ┆ … ┆ false     ┆ normal ┆ PRM     ┆ ["brawl", │
│ 0e3-59fe-b ┆            ┆            ┆ ]          ┆   ┆           ┆        ┆         ┆ "commande │
│ 3a2-2936f9 ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ r", …     │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vint…    │
│ 7582c9b0-c ┆ Organic    ┆ Sorcery    ┆ ["Sorcery" ┆ … ┆ false     ┆ normal ┆ PRM     ┆ ["command │
│ c7d-5195-9 ┆ Extinction ┆            ┆ ]          ┆   ┆           ┆        ┆         ┆ er",      │
│ cca-0f63e2 ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …      ┆ …       ┆ …         │
│ 479a51d0-7 ┆ Creature   ┆ Enchantmen ┆ ["Enchantm ┆ … ┆ false     ┆ normal ┆ CED     ┆ []        │
│ 7c6-593e-b ┆ Bond       ┆ t — Aura   ┆ ent"]      ┆   ┆           ┆        ┆         ┆           │
│ 03b-9e756d ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 8133b4a5-c ┆ Drain      ┆ Sorcery    ┆ ["Sorcery" ┆ … ┆ false     ┆ normal ┆ CED     ┆ []        │
│ 11a-57d1-b ┆ Power      ┆            ┆ ]          ┆   ┆           ┆        ┆         ┆           │
│ a11-8346ea ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 590323d2-f ┆ Feedback   ┆ Enchantmen ┆ ["Enchantm ┆ … ┆ false     ┆ normal ┆ CED     ┆ []        │
│ 47c-5cdd-9 ┆            ┆ t — Aura   ┆ ent"]      ┆   ┆           ┆        ┆         ┆           │
│ 54f-d2a831 ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ afad3ef5-4 ┆ Flight     ┆ Enchantmen ┆ ["Enchantm ┆ … ┆ false     ┆ normal ┆ CED     ┆ []        │
│ 883-54b9-b ┆            ┆ t — Aura   ┆ ent"]      ┆   ┆           ┆        ┆         ┆           │
│ 2a5-0561aa ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 88249f53-6 ┆ Invisibili ┆ Enchantmen ┆ ["Enchantm ┆ … ┆ false     ┆ normal ┆ CED     ┆ []        │
│ 9dc-5849-9 ┆ ty         ┆ t — Aura   ┆ ent"]      ┆   ┆           ┆        ┆         ┆           │
│ 71a-678c99 ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴─────────┴───────────┘

In [152]:
cards_df = cards_df.sort("name")
cards_df

shape: (104_308, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬─────────┬───────────┐
│ uuid       ┆ name       ┆ type       ┆ types      ┆ … ┆ isLegenda ┆ layout ┆ setCode ┆ legalitie │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ry        ┆ ---    ┆ ---     ┆ s         │
│ str        ┆ str        ┆ str        ┆ list[str]  ┆   ┆ ---       ┆ str    ┆ str     ┆ ---       │
│            ┆            ┆            ┆            ┆   ┆ bool      ┆        ┆         ┆ list[str] │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═════════╪═══════════╡
│ 6869d699-5 ┆ "Ach!      ┆ Enchantmen ┆ ["Enchantm ┆ … ┆ false     ┆ normal ┆ UNH     ┆ []        │
│ f2b-5a41-8 ┆ Hans,      ┆ t          ┆ ent"]      ┆   ┆           ┆        ┆         ┆           │
│ 86c-4e74b5 ┆ Run!"      ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 9551b2bb-e ┆ "Brims"    ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ []        │
│ 58f-5b0e-b ┆ Barone,    ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆           │
│ 052-63a64f ┆ Midway     ┆ Human Rog… ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆ Mobster    ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 8466f5d3-b ┆ "Brims"    ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ []        │
│ 178-5ce7-9 ┆ Barone,    ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆           │
│ 8ec-4aad1e ┆ Midway     ┆ Human Rog… ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆ Mobster    ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ a6321f1b-3 ┆ "Brims"    ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ []        │
│ 988-58dd-b ┆ Barone,    ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆           │
│ 148-f02b05 ┆ Midway     ┆ Human Rog… ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆ Mobster    ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ f064ff0b-4 ┆ "Brims"    ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ []        │
│ 0b8-5680-b ┆ Barone,    ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆           │
│ 9c7-c5ee43 ┆ Midway     ┆ Human Rog… ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆ Mobster    ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …      ┆ …       ┆ …         │
│ 893deb26-3 ┆ Éowyn,     ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTR     ┆ ["brawl", │
│ 19f-53b5-9 ┆ Lady of    ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ "commande │
│ 772-061f26 ┆ Rohan      ┆ Human Nob… ┆            ┆   ┆           ┆        ┆         ┆ r", …     │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vint…    │
│ c25ccef8-f ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ c15-5617-9 ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 77f-701cbb ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ 80f56f00-a ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ ce2-5368-8 ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 8a7-9137d6 ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ 3a2a0f4b-7 ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ 045-568f-9 ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 206-8d08aa ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ f50512c3-9 ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ 04c-563b-a ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 26e-65106a ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴─────────┴───────────┘

In [153]:
cards_df.select(pl.col("legalities"))

shape: (104_308, 1)
┌─────────────────────────────────┐
│ legalities                      │
│ ---                             │
│ list[str]                       │
╞═════════════════════════════════╡
│ []                              │
│ []                              │
│ []                              │
│ []                              │
│ []                              │
│ …                               │
│ ["brawl", "commander", … "vint… │
│ ["commander", "duel", … "vinta… │
│ ["commander", "duel", … "vinta… │
│ ["commander", "duel", … "vinta… │
│ ["commander", "duel", … "vinta… │
└─────────────────────────────────┘

In [154]:
commander_legal_cards_df = cards_df.filter(pl.col("legalities").list.contains("commander"))
commander_legal_cards_df

shape: (96_964, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬─────────┬───────────┐
│ uuid       ┆ name       ┆ type       ┆ types      ┆ … ┆ isLegenda ┆ layout ┆ setCode ┆ legalitie │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ry        ┆ ---    ┆ ---     ┆ s         │
│ str        ┆ str        ┆ str        ┆ list[str]  ┆   ┆ ---       ┆ str    ┆ str     ┆ ---       │
│            ┆            ┆            ┆            ┆   ┆ bool      ┆        ┆         ┆ list[str] │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═════════╪═══════════╡
│ 45080400-c ┆ "Lifetime" ┆ Creature — ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ ["command │
│ acf-5ae0-a ┆ Pass       ┆ Zombie     ┆ "]         ┆   ┆           ┆        ┆         ┆ er"]      │
│ 069-4c4e7a ┆ Holder     ┆ Guest      ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ ff00f069-2 ┆ "Lifetime" ┆ Creature — ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ ["command │
│ 3e7-5fad-b ┆ Pass       ┆ Zombie     ┆ "]         ┆   ┆           ┆        ┆         ┆ er"]      │
│ 76c-8225e6 ┆ Holder     ┆ Guest      ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 0ff99cfc-c ┆ "Name      ┆ Creature — ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ UNF     ┆ ["command │
│ c2d-576c-b ┆ Sticker"   ┆ Goblin     ┆ "]         ┆   ┆           ┆        ┆         ┆ er"]      │
│ 175-34de42 ┆ Goblin     ┆ Guest      ┆            ┆   ┆           ┆        ┆         ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆           │
│ 84d2e61d-4 ┆ +2 Mace    ┆ Artifact — ┆ ["Artifact ┆ … ┆ false     ┆ normal ┆ AFR     ┆ ["brawl", │
│ 6ef-5fa7-a ┆            ┆ Equipment  ┆ "]         ┆   ┆           ┆        ┆         ┆ "commande │
│ eff-7a4cd8 ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ r", …     │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vint…    │
│ 410b7a27-1 ┆ A Good Day ┆ Instant    ┆ ["Instant" ┆ … ┆ false     ┆ normal ┆ UNF     ┆ ["command │
│ 10f-53c3-8 ┆ to Pie     ┆            ┆ ]          ┆   ┆           ┆        ┆         ┆ er",      │
│ 1bd-5358e7 ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …      ┆ …       ┆ …         │
│ 893deb26-3 ┆ Éowyn,     ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTR     ┆ ["brawl", │
│ 19f-53b5-9 ┆ Lady of    ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ "commande │
│ 772-061f26 ┆ Rohan      ┆ Human Nob… ┆            ┆   ┆           ┆        ┆         ┆ r", …     │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vint…    │
│ c25ccef8-f ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ c15-5617-9 ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 77f-701cbb ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ 80f56f00-a ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ ce2-5368-8 ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 8a7-9137d6 ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ 3a2a0f4b-7 ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ 045-568f-9 ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 206-8d08aa ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
│ f50512c3-9 ┆ Éowyn, Shi ┆ Legendary  ┆ ["Creature ┆ … ┆ false     ┆ normal ┆ LTC     ┆ ["command │
│ 04c-563b-a ┆ eldmaiden  ┆ Creature — ┆ "]         ┆   ┆           ┆        ┆         ┆ er",      │
│ 26e-65106a ┆            ┆ Human Kni… ┆            ┆   ┆           ┆        ┆         ┆ "duel", … │
│ …          ┆            ┆            ┆            ┆   ┆           ┆        ┆         ┆ "vinta…   │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴─────────┴───────────┘

In [155]:
url = "https://mtgjson.com/api/v5/AllPricesToday.json"
response = requests.get(url)

BATCH_SIZE = 1000
OUTPUT_DIR = "mtgjson_card_price_batches"

# Create output directory
os.makedirs(OUTPUT_DIR, exist_ok=True)

if response.status_code == 200:
    price_data = response.json()['data']

In [156]:
import random
random_uuid = random.choice(list(price_data.keys()))
print("random UUID:", random_uuid)
print(json.dumps(price_data[random_uuid], indent=2))

random UUID: 29ee7782-955f-5e0a-8739-029b18b90e73
{
  "mtgo": {
    "cardhoarder": {
      "buylist": {},
      "retail": {
        "normal": {
          "2025-06-02": 0.03
        },
        "foil": {
          "2025-06-02": 0.02
        }
      },
      "currency": "USD"
    }
  },
  "paper": {
    "tcgplayer": {
      "buylist": {},
      "retail": {
        "normal": {
          "2025-06-02": 0.04
        },
        "foil": {
          "2025-06-02": 0.49
        }
      },
      "currency": "USD"
    },
    "cardmarket": {
      "buylist": {},
      "retail": {
        "normal": {
          "2025-06-02": 0.12
        },
        "foil": {
          "2025-06-02": 0.22
        }
      },
      "currency": "EUR"
    },
    "cardkingdom": {
      "buylist": {
        "foil": {
          "2025-06-02": 0.1
        }
      },
      "retail": {
        "normal": {
          "2025-06-02": 0.35
        },
        "foil": {
          "2025-06-02": 0.49
        }
      },
      "currency": "USD"
    },
    "cardsphere": {
      "buylist": {},
      "retail": {
        "normal": {
          "2025-06-02": 0.19
        }
      },
      "currency": "USD"
    }
  }
}

In [157]:
def extract_paper_prices(uuid, price_data):
    row = {'uuid':uuid}
    paper_price = price_data.get("paper", {})

    for vendor, vendor_price in paper_price.items():
        retail_price = vendor_price.get("retail", {})

        for version in ["normal", "foil"]:
            version_prices = retail_price.get(version, {})
            if version_prices:
                latest_date = max(version_prices.keys())
                col_name = f"{vendor}_{version}"
                row[col_name] = version_prices[latest_date]
    return row

In [158]:
rows = []
for uuid, card_data in price_data.items():
    rows.append(extract_paper_prices(uuid, card_data))

In [159]:
# Ensure all rows have consistent schemas by filling missing values with None
rows = [extract_paper_prices(uuid, price_data[uuid]) for uuid in price_data]

# Convert rows to a DataFrame, ensuring consistent schema
card_price_df = pl.DataFrame(rows, infer_schema_length=None).fill_null(0)

card_price_df.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ uuid       ┆ cardmarket ┆ cardsphere ┆ cardkingd ┆ tcgplayer ┆ cardmarke ┆ tcgplayer ┆ cardkingd │
│ ---        ┆ _normal    ┆ _normal    ┆ om_normal ┆ _normal   ┆ t_foil    ┆ _foil     ┆ om_foil   │
│ str        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ f182e364-0 ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 439-5594-a ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 6e6-75f788 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 330deaa3-d ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ d7a-52a8-b ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ fbc-b323cd ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 79e36956-b ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 91f-580f-8 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 309-7d9585 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 6afb2b4c-5 ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 30a-57d5-8 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ e7f-871239 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ b1fc2762-9 ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 2aa-5a14-8 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 509-a59cb6 ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [160]:
legal_price_df = commander_legal_cards_df.join(card_price_df, on="uuid", how="inner")

In [161]:
legal_price_df.filter(pl.col('name') == 'Gush')

shape: (8, 25)
┌────────────┬──────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ uuid       ┆ name ┆ type    ┆ types      ┆ … ┆ tcgplayer_ ┆ cardmarket ┆ tcgplayer_ ┆ cardkingdo │
│ ---        ┆ ---  ┆ ---     ┆ ---        ┆   ┆ normal     ┆ _foil      ┆ foil       ┆ m_foil     │
│ str        ┆ str  ┆ str     ┆ list[str]  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆      ┆         ┆            ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪══════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2abd9f6e-0 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 5.27       ┆ 59.93      ┆ 80.73      ┆ 109.99     │
│ 219-59e9-8 ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ fb6-737a88 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ e51fd784-e ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 1.54       ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 15a-5c41-b ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 1b6-131ede ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 8f3e2217-7 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 348-5839-9 ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ a9e-b5d438 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 62962f58-4 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 3f0-5726-a ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 8d8-533ce1 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 608fdf74-a ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 1.54       ┆ 33.31      ┆ 41.01      ┆ 0.0        │
│ 790-5d25-a ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 7c0-37ba4f ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ fc735601-b ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 2.34       ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ c81-5b80-9 ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 4d1-d854e2 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 074508d4-2 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 1.34       ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 326-536c-a ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 3c4-b2b775 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 72e22db3-a ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 046-52b2-b ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ d16-b1bb47 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
└────────────┴──────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [162]:
legal_price_df

shape: (92_197, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uuid      ┆ name      ┆ type      ┆ types     ┆ … ┆ tcgplayer ┆ cardmarke ┆ tcgplayer ┆ cardking │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _normal   ┆ t_foil    ┆ _foil     ┆ dom_foil │
│ str       ┆ str       ┆ str       ┆ list[str] ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 29924ca8- ┆ Braingeys ┆ Sorcery   ┆ ["Sorcery ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 4937-5caa ┆ er        ┆           ┆ "]        ┆   ┆           ┆           ┆           ┆          │
│ -a972-489 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ bf1…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa0bf97b- ┆ Fork      ┆ Instant   ┆ ["Instant ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 807d-5fdd ┆           ┆           ┆ "]        ┆   ┆           ┆           ┆           ┆          │
│ -a73d-262 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 21d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 519d8b44- ┆ Sedge     ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ b84a-5470 ┆ Troll     ┆ — Troll   ┆ e"]       ┆   ┆           ┆           ┆           ┆          │
│ -84b0-719 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e0b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1394796a- ┆ Two-Heade ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 534f-5e87 ┆ d Giant   ┆ — Giant   ┆ e"]       ┆   ┆           ┆           ┆           ┆          │
│ -8b41-312 ┆ of Foriys ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 58f…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f9e61d2d- ┆ Ifh-Bíff  ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ bed5-5eb8 ┆ Efreet    ┆ — Efreet  ┆ e"]       ┆   ┆           ┆           ┆           ┆          │
│ -a876-553 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 757…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ c4edc523- ┆ Bloomvine ┆ Sorcery — ┆ ["Sorcery ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ bc71-5aec ┆ Regent // ┆ Omen      ┆ "]        ┆   ┆           ┆           ┆           ┆          │
│ -80c2-22c ┆ Claim     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 663…      ┆ Terr…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 72e22db3- ┆ Gush      ┆ Instant   ┆ ["Instant ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ a046-52b2 ┆           ┆           ┆ "]        ┆   ┆           ┆           ┆           ┆          │
│ -bd16-b1b ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b47…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e8d1911d- ┆ Ajani     ┆ Legendary ┆ ["Planesw ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 3b62-5e34 ┆ Goldmane  ┆ Planeswal ┆ alker"]   ┆   ┆           ┆           ┆           ┆          │
│ -8bbb-cf2 ┆ // Ajani  ┆ ker —     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 802…      ┆ Goldma…   ┆ Ajani     ┆           ┆   ┆           ┆           ┆           ┆          │
│ c8e14900- ┆ Ajani     ┆ Legendary ┆ ["Planesw ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ b85b-5249 ┆ Goldmane  ┆ Planeswal ┆ alker"]   ┆   ┆           ┆           ┆           ┆          │
│ -85e1-c71 ┆ // Ajani  ┆ ker —     ┆           ┆   ┆           ┆           ┆           ┆          │
│ d1f…      ┆ Goldma…   ┆ Ajani     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9b3292e8- ┆ The One   ┆ Legendary ┆ ["Artifac ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 01ad-5489 ┆ Ring      ┆ Artifact  ┆ t"]       ┆   ┆           ┆           ┆           ┆          │
│ -8116-a27 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f8b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [163]:
legal_price_df = legal_price_df.select([col for col in legal_price_df.columns if "foil" not in col])
legal_price_df.filter(pl.col('name') == 'Gush')

shape: (8, 22)
┌────────────┬──────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ uuid       ┆ name ┆ type    ┆ types      ┆ … ┆ cardmarket ┆ cardsphere ┆ cardkingdo ┆ tcgplayer_ │
│ ---        ┆ ---  ┆ ---     ┆ ---        ┆   ┆ _normal    ┆ _normal    ┆ m_normal   ┆ normal     │
│ str        ┆ str  ┆ str     ┆ list[str]  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆      ┆         ┆            ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪══════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2abd9f6e-0 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 2.41       ┆ 5.2        ┆ 3.49       ┆ 5.27       │
│ 219-59e9-8 ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ fb6-737a88 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ e51fd784-e ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 1.42       ┆ 1.6        ┆ 3.49       ┆ 1.54       │
│ 15a-5c41-b ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 1b6-131ede ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 8f3e2217-7 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 348-5839-9 ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ a9e-b5d438 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 62962f58-4 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│ 3f0-5726-a ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 8d8-533ce1 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 608fdf74-a ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 1.19       ┆ 1.16       ┆ 2.49       ┆ 1.54       │
│ 790-5d25-a ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 7c0-37ba4f ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ fc735601-b ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 2.31       ┆ 2.05       ┆ 3.49       ┆ 2.34       │
│ c81-5b80-9 ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 4d1-d854e2 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 074508d4-2 ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 1.1        ┆ 1.07       ┆ 2.29       ┆ 1.34       │
│ 326-536c-a ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ 3c4-b2b775 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ 72e22db3-a ┆ Gush ┆ Instant ┆ ["Instant" ┆ … ┆ 0.0        ┆ 2124.98    ┆ 0.0        ┆ 0.0        │
│ 046-52b2-b ┆      ┆         ┆ ]          ┆   ┆            ┆            ┆            ┆            │
│ d16-b1bb47 ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
│ …          ┆      ┆         ┆            ┆   ┆            ┆            ┆            ┆            │
└────────────┴──────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [164]:
def card_finder(name: str, dataframe: pl.DataFrame):
    return dataframe.filter(pl.col('name') == f'{name}')

In [165]:
legal_price_df.columns

['uuid',
 'name',
 'type',
 'types',
 'subtypes',
 'manaCost',
 'convertedManaCost',
 'colors',
 'colorIdentity',
 'text',
 'power',
 'toughness',
 'loyalty',
 'rarity',
 'isLegendary',
 'layout',
 'setCode',
 'legalities',
 'cardmarket_normal',
 'cardsphere_normal',
 'cardkingdom_normal',
 'tcgplayer_normal']

In [166]:
legal_price_df = legal_price_df.with_columns(
    mean=pl.mean_horizontal(
        "cardmarket_normal",
        "cardsphere_normal",
        "tcgplayer_normal",
        "cardkingdom_normal",
        ignore_nulls=True
    )
)
legal_price_df

shape: (92_197, 23)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ uuid       ┆ name      ┆ type      ┆ types     ┆ … ┆ cardspher ┆ cardkingd ┆ tcgplayer ┆ mean    │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e_normal  ┆ om_normal ┆ _normal   ┆ ---     │
│ str        ┆ str       ┆ str       ┆ list[str] ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64     │
│            ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 29924ca8-4 ┆ Braingeys ┆ Sorcery   ┆ ["Sorcery ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0     │
│ 937-5caa-a ┆ er        ┆           ┆ "]        ┆   ┆           ┆           ┆           ┆         │
│ 972-489bf1 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ aa0bf97b-8 ┆ Fork      ┆ Instant   ┆ ["Instant ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0     │
│ 07d-5fdd-a ┆           ┆           ┆ "]        ┆   ┆           ┆           ┆           ┆         │
│ 73d-26221d ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 519d8b44-b ┆ Sedge     ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0     │
│ 84a-5470-8 ┆ Troll     ┆ — Troll   ┆ e"]       ┆   ┆           ┆           ┆           ┆         │
│ 4b0-719e0b ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 1394796a-5 ┆ Two-Heade ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0     │
│ 34f-5e87-8 ┆ d Giant   ┆ — Giant   ┆ e"]       ┆   ┆           ┆           ┆           ┆         │
│ b41-31258f ┆ of Foriys ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ f9e61d2d-b ┆ Ifh-Bíff  ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0     │
│ ed5-5eb8-a ┆ Efreet    ┆ — Efreet  ┆ e"]       ┆   ┆           ┆           ┆           ┆         │
│ 876-553757 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ c4edc523-b ┆ Bloomvine ┆ Sorcery — ┆ ["Sorcery ┆ … ┆ 2.12      ┆ 0.0       ┆ 0.0       ┆ 0.53    │
│ c71-5aec-8 ┆ Regent // ┆ Omen      ┆ "]        ┆   ┆           ┆           ┆           ┆         │
│ 0c2-22c663 ┆ Claim     ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ Terr…     ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 72e22db3-a ┆ Gush      ┆ Instant   ┆ ["Instant ┆ … ┆ 2124.98   ┆ 0.0       ┆ 0.0       ┆ 531.245 │
│ 046-52b2-b ┆           ┆           ┆ "]        ┆   ┆           ┆           ┆           ┆         │
│ d16-b1bb47 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ e8d1911d-3 ┆ Ajani     ┆ Legendary ┆ ["Planesw ┆ … ┆ 4.62      ┆ 0.0       ┆ 0.0       ┆ 1.155   │
│ b62-5e34-8 ┆ Goldmane  ┆ Planeswal ┆ alker"]   ┆   ┆           ┆           ┆           ┆         │
│ bbb-cf2802 ┆ // Ajani  ┆ ker —     ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ Goldma…   ┆ Ajani     ┆           ┆   ┆           ┆           ┆           ┆         │
│ c8e14900-b ┆ Ajani     ┆ Legendary ┆ ["Planesw ┆ … ┆ 4.62      ┆ 0.0       ┆ 0.0       ┆ 1.155   │
│ 85b-5249-8 ┆ Goldmane  ┆ Planeswal ┆ alker"]   ┆   ┆           ┆           ┆           ┆         │
│ 5e1-c71d1f ┆ // Ajani  ┆ ker —     ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ Goldma…   ┆ Ajani     ┆           ┆   ┆           ┆           ┆           ┆         │
│ 9b3292e8-0 ┆ The One   ┆ Legendary ┆ ["Artifac ┆ … ┆ 62.79     ┆ 0.0       ┆ 0.0       ┆ 15.6975 │
│ 1ad-5489-8 ┆ Ring      ┆ Artifact  ┆ t"]       ┆   ┆           ┆           ┆           ┆         │
│ 116-a27f8b ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [167]:
from sklearn.preprocessing import LabelEncoder

rarity_le = LabelEncoder()

rarity_encoded = rarity_le.fit_transform(legal_price_df["rarity"])

In [168]:
legal_price_df = legal_price_df.with_columns([
    pl.Series(name="rarity_encoded", values=rarity_encoded)
])
commander_legal_price_df = legal_price_df.drop("legalities")
commander_legal_price_df.head()

shape: (5, 23)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ uuid       ┆ name       ┆ type       ┆ types      ┆ … ┆ cardkingd ┆ tcgplayer ┆ mean ┆ rarity_en │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ om_normal ┆ _normal   ┆ ---  ┆ coded     │
│ str        ┆ str        ┆ str        ┆ list[str]  ┆   ┆ ---       ┆ ---       ┆ f64  ┆ ---       │
│            ┆            ┆            ┆            ┆   ┆ f64       ┆ f64       ┆      ┆ i64       │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 29924ca8-4 ┆ Braingeyse ┆ Sorcery    ┆ ["Sorcery" ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0  ┆ 3         │
│ 937-5caa-a ┆ r          ┆            ┆ ]          ┆   ┆           ┆           ┆      ┆           │
│ 972-489bf1 ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ aa0bf97b-8 ┆ Fork       ┆ Instant    ┆ ["Instant" ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0  ┆ 3         │
│ 07d-5fdd-a ┆            ┆            ┆ ]          ┆   ┆           ┆           ┆      ┆           │
│ 73d-26221d ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ 519d8b44-b ┆ Sedge      ┆ Creature — ┆ ["Creature ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0  ┆ 3         │
│ 84a-5470-8 ┆ Troll      ┆ Troll      ┆ "]         ┆   ┆           ┆           ┆      ┆           │
│ 4b0-719e0b ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ 1394796a-5 ┆ Two-Headed ┆ Creature — ┆ ["Creature ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0  ┆ 3         │
│ 34f-5e87-8 ┆ Giant of   ┆ Giant      ┆ "]         ┆   ┆           ┆           ┆      ┆           │
│ b41-31258f ┆ Foriys     ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ f9e61d2d-b ┆ Ifh-Bíff   ┆ Creature — ┆ ["Creature ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0  ┆ 3         │
│ ed5-5eb8-a ┆ Efreet     ┆ Efreet     ┆ "]         ┆   ┆           ┆           ┆      ┆           │
│ 876-553757 ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
│ …          ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [169]:
card_finder("Sheoldred, the Apocalypse", commander_legal_price_df)

shape: (8, 23)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ uuid       ┆ name      ┆ type      ┆ types     ┆ … ┆ cardkingd ┆ tcgplayer ┆ mean    ┆ rarity_en │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ om_normal ┆ _normal   ┆ ---     ┆ coded     │
│ str        ┆ str       ┆ str       ┆ list[str] ┆   ┆ ---       ┆ ---       ┆ f64     ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆         ┆ i64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ 9408edd9-f ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 84.99     ┆ 74.36     ┆ 72.3525 ┆ 2         │
│ 629-5231-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 827-1ea121 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1a21a7f0-f ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 119.99    ┆ 101.26    ┆ 75.6175 ┆ 2         │
│ 5f6-5107-9 ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 06b-5a33b9 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 4b20d43c-a ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 74.99     ┆ 69.64     ┆ 67.4975 ┆ 2         │
│ 70f-56ec-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 01c-439d43 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 228e2ce5-f ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 17.0    ┆ 2         │
│ 36d-5ac8-9 ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ ba3-cc2ad2 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 2dfde2ee-e ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 84.99     ┆ 75.48     ┆ 55.8925 ┆ 2         │
│ 093-558e-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 1a1-2d018e ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ c0a8a0d5-4 ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 79.99     ┆ 65.2      ┆ 68.75   ┆ 2         │
│ a99-52cb-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ b9b-8faad4 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 0eb3feb0-d ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0     ┆ 2         │
│ 605-55fe-8 ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 844-098c91 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 8685cc2b-7 ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0     ┆ 2         │
│ f3e-5f8c-a ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ bec-836cd7 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [170]:
# Step 1: Count number of non-null price columns for each row
price_columns = ["cardmarket_normal", "cardsphere_normal", "cardkingdom_normal", "tcgplayer_normal"]

price_df_filtered = commander_legal_price_df.filter(
    pl.all_horizontal(*price_columns) != 0.0
)
price_df_filtered

shape: (63_017, 23)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ uuid       ┆ name       ┆ type      ┆ types     ┆ … ┆ cardkingd ┆ tcgplayer ┆ mean   ┆ rarity_en │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ om_normal ┆ _normal   ┆ ---    ┆ coded     │
│ str        ┆ str        ┆ str       ┆ list[str] ┆   ┆ ---       ┆ ---       ┆ f64    ┆ ---       │
│            ┆            ┆           ┆           ┆   ┆ f64       ┆ f64       ┆        ┆ i64       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ ea75b13d-b ┆ Abyssal    ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.59      ┆ 0.42      ┆ 0.485  ┆ 3         │
│ 141-5f76-8 ┆ Hunter     ┆ — Human   ┆ e"]       ┆   ┆           ┆           ┆        ┆           │
│ 6db-a19c62 ┆            ┆ Assassin  ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ ceba66ba-6 ┆ Acidic     ┆ Artifact  ┆ ["Artifac ┆ … ┆ 0.49      ┆ 0.36      ┆ 0.5425 ┆ 3         │
│ 8ab-5d20-9 ┆ Dagger     ┆           ┆ t"]       ┆   ┆           ┆           ┆        ┆           │
│ 543-baeafa ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 5e7d26fa-2 ┆ Afiya      ┆ Enchantme ┆ ["Enchant ┆ … ┆ 1.29      ┆ 0.94      ┆ 1.2075 ┆ 3         │
│ b75-546a-b ┆ Grove      ┆ nt        ┆ ment"]    ┆   ┆           ┆           ┆        ┆           │
│ 4c4-a6b3bb ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 5476b4a0-5 ┆ Afterlife  ┆ Instant   ┆ ["Instant ┆ … ┆ 0.35      ┆ 0.26      ┆ 0.28   ┆ 5         │
│ ce9-5b16-9 ┆            ┆           ┆ "]        ┆   ┆           ┆           ┆        ┆           │
│ 272-5d2be6 ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 635ec7c0-5 ┆ Agility    ┆ Enchantme ┆ ["Enchant ┆ … ┆ 0.35      ┆ 0.12      ┆ 0.195  ┆ 1         │
│ 56d-50b1-a ┆            ┆ nt — Aura ┆ ment"]    ┆   ┆           ┆           ┆        ┆           │
│ e98-552589 ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …      ┆ …         │
│ f825fa94-a ┆ Neriv,     ┆ Legendary ┆ ["Creatur ┆ … ┆ 0.99      ┆ 1.67      ┆ 1.345  ┆ 2         │
│ 2a1-5491-9 ┆ Crackling  ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆        ┆           │
│ ff6-748ab2 ┆ Vanguard   ┆ — Spirit  ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆ Dr…       ┆           ┆   ┆           ┆           ┆        ┆           │
│ 733b4113-7 ┆ Shiko and  ┆ Legendary ┆ ["Creatur ┆ … ┆ 0.99      ┆ 1.28      ┆ 1.2375 ┆ 2         │
│ 568-5b63-9 ┆ Narset,    ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆        ┆           │
│ c27-11eee3 ┆ Unified    ┆ — Human   ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆ Spi…      ┆           ┆   ┆           ┆           ┆        ┆           │
│ d292eed1-c ┆ Ureni of   ┆ Legendary ┆ ["Creatur ┆ … ┆ 37.99     ┆ 23.07     ┆ 29.655 ┆ 2         │
│ 527-5384-b ┆ the        ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆        ┆           │
│ 376-5aaff0 ┆ Unwritten  ┆ — Spirit  ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆ Dr…       ┆           ┆   ┆           ┆           ┆        ┆           │
│ 6428db5c-a ┆ Zurgo Stor ┆ Legendary ┆ ["Creatur ┆ … ┆ 8.49      ┆ 8.02      ┆ 7.8475 ┆ 2         │
│ 7dd-54eb-9 ┆ mrender    ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆        ┆           │
│ ca8-c85637 ┆            ┆ — Orc     ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆ Warri…    ┆           ┆   ┆           ┆           ┆        ┆           │
│ 8c4e8f73-7 ┆ Betor,     ┆ Legendary ┆ ["Creatur ┆ … ┆ 3.49      ┆ 4.06      ┆ 4.455  ┆ 2         │
│ 016-5d26-9 ┆ Ancestor's ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆        ┆           │
│ 872-bf90c4 ┆ Voice      ┆ — Spirit  ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆            ┆ Dr…       ┆           ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [171]:
card_finder("Sheoldred, the Apocalypse", price_df_filtered)

shape: (3, 23)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ uuid       ┆ name      ┆ type      ┆ types     ┆ … ┆ cardkingd ┆ tcgplayer ┆ mean    ┆ rarity_en │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ om_normal ┆ _normal   ┆ ---     ┆ coded     │
│ str        ┆ str       ┆ str       ┆ list[str] ┆   ┆ ---       ┆ ---       ┆ f64     ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆         ┆ i64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ 9408edd9-f ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 84.99     ┆ 74.36     ┆ 72.3525 ┆ 2         │
│ 629-5231-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 827-1ea121 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ 4b20d43c-a ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 74.99     ┆ 69.64     ┆ 67.4975 ┆ 2         │
│ 70f-56ec-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ 01c-439d43 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
│ c0a8a0d5-4 ┆ Sheoldred ┆ Legendary ┆ ["Creatur ┆ … ┆ 79.99     ┆ 65.2      ┆ 68.75   ┆ 2         │
│ a99-52cb-b ┆ , the Apo ┆ Creature  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│ b9b-8faad4 ┆ calypse   ┆ — Phyrexi ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆           ┆ an…       ┆           ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [173]:
lowest_mean_prices_df = (
    price_df_filtered.sort("mean")
    .group_by("name")
    .first()
)
lowest_mean_prices_df

shape: (28_107, 23)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ name       ┆ uuid      ┆ type      ┆ types     ┆ … ┆ cardkingd ┆ tcgplayer ┆ mean    ┆ rarity_en │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ om_normal ┆ _normal   ┆ ---     ┆ coded     │
│ str        ┆ str       ┆ str       ┆ list[str] ┆   ┆ ---       ┆ ---       ┆ f64     ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆         ┆ i64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ Mite       ┆ 86cd1f91- ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.59      ┆ 0.38      ┆ 0.4625  ┆ 3         │
│ Overseer   ┆ 6ffc-530c ┆ —         ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│            ┆ -8339-eb1 ┆ Phyrexian ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ 365…      ┆ Soldier   ┆           ┆   ┆           ┆           ┆         ┆           │
│ Stalking   ┆ e0e57422- ┆ Land      ┆ ["Land"]  ┆ … ┆ 0.35      ┆ 0.19      ┆ 0.2225  ┆ 5         │
│ Stones     ┆ 1765-5c0c ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ -96a8-75c ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ 581…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Migratory  ┆ 13f004b7- ┆ Sorcery   ┆ ["Sorcery ┆ … ┆ 0.35      ┆ 0.08      ┆ 0.15    ┆ 5         │
│ Route      ┆ 5c4a-52b7 ┆           ┆ "]        ┆   ┆           ┆           ┆         ┆           │
│            ┆ -ba65-4e2 ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ bfc…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Abzan      ┆ db8ad183- ┆ Instant   ┆ ["Instant ┆ … ┆ 0.35      ┆ 0.11      ┆ 0.1625  ┆ 5         │
│ Charm      ┆ ae1e-5b9e ┆           ┆ "]        ┆   ┆           ┆           ┆         ┆           │
│            ┆ -9fe5-10a ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ d4a…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Take Heart ┆ 15785dfb- ┆ Instant   ┆ ["Instant ┆ … ┆ 0.35      ┆ 0.03      ┆ 0.135   ┆ 1         │
│            ┆ 9df8-5931 ┆           ┆ "]        ┆   ┆           ┆           ┆         ┆           │
│            ┆ -8560-2ce ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ 824…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ Taunting   ┆ db08ba19- ┆ Sorcery   ┆ ["Sorcery ┆ … ┆ 44.99     ┆ 39.77     ┆ 33.1775 ┆ 3         │
│ Challenge  ┆ fae8-59ba ┆           ┆ "]        ┆   ┆           ┆           ┆         ┆           │
│            ┆ -95f1-abc ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ bce…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Lunar      ┆ 9d29ea37- ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.49      ┆ 0.09      ┆ 0.215   ┆ 3         │
│ Hatchling  ┆ 79ed-5456 ┆ — Alien   ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│            ┆ -bde9-027 ┆ Beast     ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ 6a2…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Cavern     ┆ 7cbb7cbb- ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.35      ┆ 0.05      ┆ 0.155   ┆ 1         │
│ Thoctar    ┆ 9b54-5877 ┆ — Beast   ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│            ┆ -a996-2cd ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ 6ea…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Char       ┆ 36751078- ┆ Instant   ┆ ["Instant ┆ … ┆ 0.49      ┆ 0.27      ┆ 0.3175  ┆ 3         │
│            ┆ a55a-5730 ┆           ┆ "]        ┆   ┆           ┆           ┆         ┆           │
│            ┆ -8d67-66d ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ e03…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Mindleech  ┆ 30ce6301- ┆ Creature  ┆ ["Creatur ┆ … ┆ 0.35      ┆ 0.06      ┆ 0.1325  ┆ 1         │
│ Ghoul      ┆ 4b05-5a5d ┆ — Zombie  ┆ e"]       ┆   ┆           ┆           ┆         ┆           │
│            ┆ -b061-852 ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ fd6…      ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘